# docs https://circleci.com/docs/2.0/language-javascript/ 
defaults: &defaults
  docker:
      - image: circleci/node:8

version: 2
jobs:
  prepare: 
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
        keys:
          - v2-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
        paths:
          - node_modules
        key: v2-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
        root: .
        paths:
          - node_modules

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
        at: .
      - run: yarn build
      - persist_to_workspace:
        root: .
        paths:
          - dist
  
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
        at: .
      - run: yarn test
      - store_test_results:
        root: test_results

workflows: 
  version: 2
  build_accept_deploy:
    jobs:
      - prepare
      - build:
        requiresL
          - test
      -test:
        require:
          - prepare

      